export const SERVICE_COMPONENTS_FETCH_ALL = 'SERVICE_COMPONENTS_FETCH_ALL';
export const SERVICE_COMPONENTS_CREATE_ONE = 'SERVICE_COMPONENTS_CREATE_ONE';
export const SERVICE_COMPONENTS_DELETE_ONE = 'SERVICE_COMPONENTS_DELETE_ONE';
export const SERVICE_COMPONENTS_SELECT_ONE = 'SERVICE_COMPONENTS_SELECT_ONE';

export const SERVICE_COMPONENTS_CURRENT_COLLECTION_ID = 'designer.current.component';
export const SERVICE_COMPONENTS_COLLECTION_ID = 'designer.components';
