export const SERVICE_FETCH_ALL = 'SERVICE_ROUTES_FETCH_ALL';
export const SERVICE_CREATE_ONE = 'SERVICE_ROUTES_CREATE_ONE';
export const SERVICE_DELETE_ONE = 'SERVICE_ROUTES_DELETE_ONE';
export const SERVICE_SELECT_ONE = 'SERVICE_ROUTES_SELECT_ONE';

export const SERVICE_CURRENT_COLLECTION_ID = 'routes.current';
export const SERVICE_COLLECTION_ID = 'routes.all';
