export const SERVICE_FETCH_ALL = 'SERVICE_EXPRESSIONS_FETCH_ALL';
export const SERVICE_CREATE_ONE = 'SERVICE_EXPRESSIONS_CREATE_ONE';
export const SERVICE_DELETE_ONE = 'SERVICE_EXPRESSIONS_DELETE_ONE';
export const SERVICE_SELECT_ONE = 'SERVICE_EXPRESSIONS_SELECT_ONE';

export const SERVICE_CURRENT_COLLECTION_ID = 'designer.expressions.current';
export const SERVICE_COLLECTION_ID = 'designer.expressions.all';
