export const SERVICE_FETCH_ALL = 'SERVICE_SAGAS_FETCH_ALL';
export const SERVICE_CREATE_ONE = 'SERVICE_SAGAS_CREATE_ONE';
export const SERVICE_DELETE_ONE = 'SERVICE_SAGAS_DELETE_ONE';
export const SERVICE_SELECT_ONE = 'SERVICE_SAGAS_SELECT_ONE';

export const SERVICE_CURRENT_COLLECTION_ID = 'SAGAS.current';
export const SERVICE_COLLECTION_ID = 'SAGAS.all';
