export const SERVICE_FETCH_ALL = 'SERVICE_PROPS_FETCH_ALL';
export const SERVICE_CREATE_ONE = 'SERVICE_PROPS_CREATE_ONE';
export const SERVICE_DELETE_ONE = 'SERVICE_PROPS_DELETE_ONE';
export const SERVICE_SELECT_ONE = 'SERVICE_PROPS_SELECT_ONE';

export const SERVICE_CURRENT_COLLECTION_ID = 'props.current';
export const SERVICE_COLLECTION_ID = 'props.all';
